# config/config.yaml
# seed: 42

# paths:
#   qlib_dir: "/home/ec2-user/.qlib/qlib_data/us_data"     # 日频库
#   features_day: "artifacts/features_day.parquet"         # 特征/标签产物
#   preds_dir: "artifacts/preds/weekly"                    # 预测输出目录
#   reports_dir: "backtest/reports"                        # 回测报告目录（回测侧用）

# universe:
#   instruments_file: "~/.qlib/qlib_data/us_data/instruments/all.txt"  # 可留空
#   min_adv: 1_000_000          # 过滤低流动性（按美元或股数，视你实现）

# data:
#   freq: "day"
#   price_cols: ["$open","$high","$low","$close","$vwap","$volume"]
#   label: "y_fwd_5"            # 周频标签
#   features:                   # 可继续扩充
#     - mom_20
#     - mom_60
#     - vol_20
#     - vol_60
#     - rng_hl
#     - logv
#     - logv_zn_20
#     - adv_20
#     - vwap_spread
#     - oc
#     - upper_shadow
#     - lower_shadow
#     - ma5_gap
#     - ma20_gap

# preprocess:
#   winsor: 0.01                # 横截面去极值阈
#   zscore: true
#   neutralize:
#     enable: true
#     exposures: ["mkt_beta_60", "mkt_beta_60", "ln_dollar_vol_20", "ind_*"]             # 若特征包含 ln_mktcap / beta / sector_onehot 可填，比如 ["ln_mktcap"],如果有行业，再加 ind_*

# walk_forward:
#   # 严格时序：训练起点 → 首次调仓（初次窗口必须覆盖足够样本）
#   train_start: "2014-01-01"
#   first_rebalance: "2017-01-06"   # 第一周五；之后按 weekday 滚动
#   end_date: "2024-12-31"
#   rebalance_weekday: 4            # 0=Mon ... 4=Fri
#   min_train_obs: 50000            # 横截面样本数阈值，防止太少就训练
#   max_train_years: null           # 可选：设置为 5 做滑窗；null=扩窗

# model:
#   type: "lgbm"
#   params:
#     n_estimators: 400
#     learning_rate: 0.05
#     max_depth: -1
#     num_leaves: 63
#     subsample: 0.8
#     colsample_bytree: 0.8
#     reg_lambda: 1.0
#     reg_alpha: 0.0
#     min_child_samples: 80
#   early_stopping: 50
#   test_size_per_date: 0.0   # 横截面不切分单日；用时间滚动做 OOS

# ranking:
#   top_k: 20
#   use_weight_hint: false

# outputs:
#   write_rank_


# 全局默认策略配置
strategies:
  # 默认策略：XSecRebalance（多空再平衡策略）
  xsec_rebalance:
    selection:
      top_k: 50
      short_k: 0
      membership_buffer: 0.25
      use_rank: "auto"   # "auto" | "rank" | "score"
    
    entry:
      # 入场策略协调器配置
      enabled_strategies: ["icdf_equal"]
      strategy_weights:
        icdf_equal: 1.0
      
      # ICDF/等权重策略配置
      icdf_equal:
        neutralize_items: ["beta", "sector"]
        ridge_lambda: 1e-6
        top_k: 50
        short_k: 0
        membership_buffer: 0.25
        selection_use_rank_mode: "auto"
        long_exposure: 1.0
        short_exposure: -1.0
        max_pos_per_name: 0.05
        weight_scheme: "equal"
        smooth_eta: 0.6
        target_vol: 0.0
        leverage_cap: 2.0
        hard_cap: false
    
    exit_strategies:
      tech_stop_loss:
        atr_multiplier: 2.0
        atr_period: 14
        ma_stop_period: 20
        bollinger_period: 20
        bollinger_std: 2.0
        rsi_period: 14
        rsi_overbought: 70.0
        rsi_oversold: 30.0
        enabled_methods: ["atr", "ma", "bollinger", "rsi"]
      
      volatility_exit:
        vol_multiplier: 2.0
        vol_period: 20
        market_vol_period: 63
        vol_filter_threshold: 0.3
        max_position_days: 63
        enabled_methods: ["vol_stop", "market_vol", "vol_filter", "time_exit"]
      
      enabled_strategies: ["tech_stop_loss", "volatility_exit"]

  # 策略1：长线基础策略
  long_only_baseline:
    selection:
      top_k: 50
      short_k: 0
      membership_buffer: 0.25
      use_rank: "auto"   # "auto" | "rank" | "score"
    
    entry:
      # 入场策略协调器配置
      enabled_strategies: ["icdf_equal"]
      strategy_weights:
        icdf_equal: 1.0
      
      # ICDF/等权重策略配置
      icdf_equal:
        neutralize_items: ["beta", "sector"]
        ridge_lambda: 1e-6
        top_k: 50
        short_k: 0
        membership_buffer: 0.25
        selection_use_rank_mode: "auto"
        long_exposure: 1.0
        short_exposure: -1.0
        max_pos_per_name: 0.05
        weight_scheme: "equal"
        smooth_eta: 0.6
        target_vol: 0.0
        leverage_cap: 2.0
        hard_cap: false
    
    exit_strategies:
      tech_stop_loss:
        atr_multiplier: 2.0
        atr_period: 14
        ma_stop_period: 20
        bollinger_period: 20
        bollinger_std: 2.0
        rsi_period: 14
        rsi_overbought: 70.0
        rsi_oversold: 30.0
        enabled_methods: ["atr", "ma", "bollinger", "rsi"]
      
      volatility_exit:
        vol_multiplier: 2.0
        vol_period: 20
        market_vol_period: 63
        vol_filter_threshold: 0.3
        max_position_days: 63
        enabled_methods: ["vol_stop", "market_vol", "vol_filter", "time_exit"]
      
      enabled_strategies: ["tech_stop_loss", "volatility_exit"]

  # 策略2：长短结合策略
  long_short_tv08:
    selection:
      top_k: 40
      short_k: 8
      membership_buffer: 0.40
      use_rank: "auto"
    
    entry:
      # 入场策略协调器配置
      enabled_strategies: ["icdf_equal"]
      strategy_weights:
        icdf_equal: 1.0
      
      # ICDF/等权重策略配置
      icdf_equal:
        neutralize_items: ["beta", "sector", "size"]
        ridge_lambda: 1e-6
        top_k: 40
        short_k: 8
        membership_buffer: 0.40
        selection_use_rank_mode: "auto"
        long_exposure: 1.0
        short_exposure: -0.8
        max_pos_per_name: 0.04
        weight_scheme: "equal"
        smooth_eta: 0.7
        target_vol: 0.15
        leverage_cap: 1.5
        hard_cap: true
    
    exit_strategies:
      tech_stop_loss:
        atr_multiplier: 1.8
        atr_period: 10
        ma_stop_period: 15
        bollinger_period: 20
        bollinger_std: 1.8
        rsi_period: 10
        rsi_overbought: 75.0
        rsi_oversold: 25.0
        enabled_methods: ["atr", "ma", "bollinger"]
      
      volatility_exit:
        vol_multiplier: 1.5
        vol_period: 14
        market_vol_period: 50
        vol_filter_threshold: 0.25
        max_position_days: 50
        enabled_methods: ["vol_stop", "time_exit"]
      
      enabled_strategies: ["tech_stop_loss", "volatility_exit"]

  # 策略3：ICDF激进策略
  icdf_aggressive:
    selection:
      top_k: 80
      short_k: 20
      membership_buffer: 0.20
      use_rank: "rank"
    
    entry:
      # 入场策略协调器配置
      enabled_strategies: ["icdf_equal"]
      strategy_weights:
        icdf_equal: 1.0
      
      # ICDF/等权重策略配置
      icdf_equal:
        neutralize_items: ["beta", "sector", "size", "liq"]
        ridge_lambda: 1e-5
        top_k: 80
        short_k: 20
        membership_buffer: 0.20
        selection_use_rank_mode: "rank"
        long_exposure: 1.2
        short_exposure: -0.8
        max_pos_per_name: 0.03
        weight_scheme: "icdf"
        smooth_eta: 0.5
        target_vol: 0.20
        leverage_cap: 2.5
        hard_cap: true
    
    exit_strategies:
      tech_stop_loss:
        atr_multiplier: 2.2
        atr_period: 20
        ma_stop_period: 25
        bollinger_period: 25
        bollinger_std: 2.2
        rsi_period: 14
        rsi_overbought: 80.0
        rsi_oversold: 20.0
        enabled_methods: ["atr", "bollinger", "rsi"]
      
      volatility_exit:
        vol_multiplier: 2.5
        vol_period: 30
        market_vol_period: 90
        vol_filter_threshold: 0.35
        max_position_days: 30
        enabled_methods: ["vol_stop", "market_vol", "vol_filter"]
      
      enabled_strategies: ["tech_stop_loss", "volatility_exit"]

# 全局默认配置（向后兼容）
selection:
  top_k: 50
  short_k: 0
  membership_buffer: 0.25
  use_rank: "auto"
