# config/config.yaml
# seed: 42

# paths:
#   qlib_dir: "/home/ec2-user/.qlib/qlib_data/us_data"     # 
#   features_day: "artifacts/features_day.parquet"         # /
#   preds_dir: "artifacts/preds/weekly"                    # 
#   reports_dir: "backtest/reports"                        # 

# universe:
#   instruments_file: "~/.qlib/qlib_data/us_data/instruments/all.txt"  # 
#   min_adv: 1_000_000          # 

# data:
#   freq: "day"
#   price_cols: ["$open","$high","$low","$close","$vwap","$volume"]
#   label: "y_fwd_5"            # 
#   features:                   # 
#     - mom_20
#     - mom_60
#     - vol_20
#     - vol_60
#     - rng_hl
#     - logv
#     - logv_zn_20
#     - adv_20
#     - vwap_spread
#     - oc
#     - upper_shadow
#     - lower_shadow
#     - ma5_gap
#     - ma20_gap

# preprocess:
#   winsor: 0.01                # 
#   zscore: true
#   neutralize:
#     enable: true
#     exposures: ["mkt_beta_60", "mkt_beta_60", "ln_dollar_vol_20", "ind_*"]             #  ln_mktcap / beta / sector_onehot  ["ln_mktcap"], ind_*

# walk_forward:
#   #   
#   train_start: "2014-01-01"
#   first_rebalance: "2017-01-06"   #  weekday 
#   end_date: "2024-12-31"
#   rebalance_weekday: 4            # 0=Mon ... 4=Fri
#   min_train_obs: 50000            # 
#   max_train_years: null           #  5 null=

# model:
#   type: "lgbm"
#   params:
#     n_estimators: 400
#     learning_rate: 0.05
#     max_depth: -1
#     num_leaves: 63
#     subsample: 0.8
#     colsample_bytree: 0.8
#     reg_lambda: 1.0
#     reg_alpha: 0.0
#     min_child_samples: 80
#   early_stopping: 50
#   test_size_per_date: 0.0   #  OOS

# ranking:
#   top_k: 20
#   use_weight_hint: false

# outputs:
#   write_rank_


# 
strategies:
  # XSecRebalance
  xsec_rebalance:
    selection:
      top_k: 10
      short_k: 0
      membership_buffer: 0.35
      use_rank: "auto"
    entry:
      # 
      neutralize_items: ["beta", "sector", "size"]
      ridge_lambda: 1e-6
      enabled_strategies: ["icdf_equal"]
      strategy_weights:
        icdf_equal: 1.0
      icdf_equal:
        neutralize_items: ["beta", "sector", "size"]
        ridge_lambda: 1e-6
        top_k: 50
        short_k: 0
        membership_buffer: 0.35
        selection_use_rank_mode: "auto"
        long_exposure: 1.0
        short_exposure: 0.0
        max_pos_per_name: 0.04
        weight_scheme: "icdf"
        smooth_eta: 0.65
        target_vol: 0.11
        leverage_cap: 1.8
        hard_cap: true
      filters:
        sector_liq_exclude:
          Communication Services: [0, 1, 2, 3, 4]
          Consumer Discretionary: [0, 1, 2, 3, 4]
          Consumer Staples: [0, 1, 2, 3]
          Energy: [0, 1, 2, 3, 4]
          Financials: [0, 1, 2, 3]
          Health Care: [0, 1, 2, 3, 4]
          Industrials: [0, 2, 3, 4]
          Information Technology: [0, 2]
          Materials: [0, 1, 2, 3, 4]
          Real Estate: [0, 1, 4]
          Utilities: [0, 1, 2, 4]

